name: "[52n-master -> latest] Builds GeoNode Docker Images"

concurrency:
  group: "geonode_build_master"
  cancel-in-progress: true

env:
  TAG: latest

on:
  push:
    branches:
      - "52n-master"

jobs:
  build_and_push_geonode:
    runs-on: ubuntu-22.04
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: build and push geonode
        uses: ./.github/actions/build_and_push
        with:
          image: 52north/geonode
          tags: ${{ env.TAG }}
          oci_title: "52°North GeoNode image"
          oci_description: "GeoNode built from 52n fork"
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN_52N_MASTER }}
      
  build_and_push_nginx:
    runs-on: ubuntu-22.04
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: build and push nginx
        uses: ./.github/actions/build_and_push
        with:
          dockerfile: ./scripts/docker/nginx/Dockerfile
          dockercontext: ./scripts/docker/nginx/
          image: 52north/geonode-nginx
          tags: ${{ env.TAG }}
          oci_title: "52°North Nginx image for GeoNode"
          oci_description: "Nginx built for GeoNode from a 52n fork"
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN_52N_MASTER }}

  build_and_push_geoserver:
    runs-on: ubuntu-22.04
    env:
      IMAGE: 52north/geonode-geoserver
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: build and push geoserver
        uses: ./.github/actions/build_and_push
        with:
          dockerfile: ./scripts/docker/geoserver/Dockerfile
          dockercontext: ./scripts/docker/geoserver/
          image: 52north/geonode-geoserver
          tags: ${{ env.TAG }}
          oci_title: "52°North GeoServer image for GeoNode"
          oci_description: "GeoServer built for GeoNode from a 52n fork"
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN_52N_MASTER }}
